# Generated by Django 4.2.18 on 2025-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='remark',
            field=models.TextField(blank=True, max_length=512, verbose_name='Remark'),
        ),
    ]
