# Generated by Django 4.2.18 on 2025-02-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_alter_a_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='detail',
            field=models.JSONField(blank=True, null=True, verbose_name='Detail'),
        ),
    ]
